language: node_js
node_js:
  - "node"

os:
  - linux

cache:
  directories:
    - "node_modules"

script:
  - "npm run test-ci"
  - "npm run lint"

before_install:
  # Recompile modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"

install:
  - npm install -g coveralls
  - npm install -g codecov


after_script:
  - cat ./coverage/lcov.info | coveralls
  - codecov
